apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      env:
        - name: TREE1
          valueFrom: 
            configMapKeyRef:
              name: trauerweide 
              key: tree 
      volumeMounts:
        - mountPath: /etc/brike/
          name: brike

  volumes:
     - name: brike
       configMap:
         name: birke
